services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=spring_modulith'
      - 'MYSQL_PASSWORD=spring_modulith'
      - 'MYSQL_ROOT_PASSWORD=1234'
      - 'MYSQL_USER=myuser'
    ports:
      - "3307:3306"
    
    volumes:
      - /c/tmp/spring_modulith:/var/lib/mysql